[[headers]]
  # Override cache duration for assets with periods in the filename (i.e. static assets)
  for = "/*.*"
    [headers.values]
    cache-control = "public,max-age=31536000‬00"
    Accept-Encoding = "br,gzip"
